name: Create envfile

on: [ push ]

jobs:

  create-envfile:

    runs-on: ubuntu-latest

    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          envkey_VITE_LAST_UPDATE: ${{ steps.date.outputs.date }}
          directory: .
          file_name: .env
          fail_on_empty: true
          sort_keys: false
