name: Create envfile

on: [ push ]

jobs:

  create-envfile:

    runs-on: ubuntu-latest

    steps:
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          envkey_VITE_LAST_UPDATE: ${{ steps.current-time.outputs.time }}
          directory: .
          file_name: .env
          fail_on_empty: true
          sort_keys: false
        run: echo "${{ steps.current-time.outputs.time }}"