name: Create envfile

on: [ push ]

jobs:

  create-envfile:

    runs-on: ubuntu-latest

    steps:
      - name: Set current time
        id: set_time
        run: echo "CURRENT_TIME=$(date +"%B %e, %Y")" >> $GITHUB_ENV

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          envkey_VITE_LAST_UPDATE: ${{ steps.set_time.outputs.CURRENT_TIME }}
          directory: .
          file_name: .env
          fail_on_empty: true
          sort_keys: false